### ISSUE TITLE
Checklist Of Content To Include

### ISSUE THREAD

**Issue by O957** [AFg6K7h4fhy2/AFg6K7h4fhy2-Template#1]
This issue is an ongoing list of content to include in my personal template repository. Boxes are checked once an initial implementation decision has been made and executed. 

* [x] General issue template
* [ ] Repository decisions template
* [ ] Bug Reporting template
* [x] CONTRIBUTING template
* [x] CODEOWNERS file
* [x] `.gitignore` content ([discussion here](https://github.com/AFg6K7h4fhy2/AFg6K7h4fhy2-Template/discussions/2))
* [ ]  `README.md` content
* [x]  Inclusion of `.pre-commit`
* [ ] GitHub workflows content
* [ ] GitHub actions content
* [ ] Initial folder structure
* [ ] Baseline documentation guides (see [here](https://www.writethedocs.org/) and [here](https://diataxis.fr/))
* [ ] ?Dockerfile and/or Makefile
* [ ] LICENSE
* [ ] CHANGELOG template
* [ ] Security template
* [ ] Code quality tools
* [ ] Directory naming scheme
